vignette_params:
  version: 1
  counts_per_type:
    ref_con: 64
    ref_emp: 51
    comply: 44

  trust:
    t_star: 0.70754717
    band: 0.10000000
    band_low: 0.60754717
    band_high: 0.80754717

  threshold:
    logistic:
      intercept: 3.20503554
      slope_risk: 0.22611886
      offset_empathic: 0.19001078
      offset_constructive: -0.19001078
    normalization:
      risk_mean: 5.06918239
      risk_std: 1.65399209

  blame:
    intercept: 0.48738111
    cond_empathic: -0.14835393
    cond_constructive: -0.16751695
    risk_slope: -0.13765945
    risk_slope_comply: -0.11194738
